name: Deploy Vite ReactJs to Plesk

on:
  push:
    branches:
      - main # branch ที่ต้องการ deploy

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PLESK_DEPLOYMENT

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3) Install dependencies (npm)
      - name: Install dependencies
        run: npm ci

      # 4) Build Vite React
      - name: Build Vite React
        run: npm run build

      # 5) Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: PLESK_DEPLOYMENT

    steps:
      - name: List files after download
        run: ls -R

      # 1) Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      # 2) Deploy dist -> Plesk httpdocs
      - name: Deploy to Plesk via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /httpdocs/
